[phases.setup]
nixPkgs = ["sqlite", "python3"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c \"from database import db; print('✅ База данных инициализирована')\""]

[start]
cmd = "python bot.py"

[environment]
BOT_TOKEN = "8246923680:AAGKcVwu0xz0qEi-AqEqdm8EUJqNU2_h6oA"
CHANNEL_ID = "-1003360198094"